### PR TITLE
airbyte-to-flow: terminate child on idle timeout

### PR DESCRIPTION
**Pull request by mdibaiee**

### CODE REVIEW

**Comment by jgraettinger** [comment]
Please comment on how this was tested.

**Comment by mdibaiee** [comment]
Created a modified image of `source-hello-world` which has `time.Sleep(time.Millisecond * 1000 *  60 * 15)` at the end of its loop, and uses the `airbyte-to-flow:7cee78d` from this pull-request. Build this connector, and run the following catalog:

```
---
captures:
  acmeCo/source-hello-world:
    endpoint:
      connector:
        image: "ghcr.io/estuary/source-hello-world:local"
        config:
          greetings: 100
    bindings:
      - resource:
          stream: greetings
          syncMode: incremental
        target: acmeCo/greetings
collections:
  acmeCo/greetings:
    schema:
      properties:
        count:
          type: integer
        message:
          type: string
      required:
        - count
        - message
      type: object
    key:
      - /count

storageMappings:
    "":
        stores:
            - provider: S3
              bucket: acmeCo-source-hubspot
```

Wait 10 minutes, and the logs write:

```
{"_meta":{"uuid":"a57ce6b8-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.036133209Z","level":"warn","message":"connector has been idle for the past 10 minutes. restarting."}
{"_meta":{"uuid":"a57ed0fe-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.041741751Z","level":"debug","message":"atf: killing child process"}
{"_meta":{"uuid":"a57f28d8-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.061703251Z","level":"debug","message":"atf: connector_runner done"}
{"_meta":{"uuid":"a57f9aa2-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.064642251Z","level":"info","message":"atf exiting"}
{"_meta":{"uuid":"a5803c78-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.068999293Z","level":"debug","message":"connector exited","fields":{"module":"connector_init::rpc","status":"exit status: 0"}}
{"_meta":{"uuid":"a58065d6-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.070173459Z","level":"debug","message":"finished reading connector output","fields":{"module":"connector_init::codec"}}
{"_meta":{"uuid":"a580c512-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.073150Z","level":"debug","message":"capture transaction committing updating driver checkpoint only","fields":{}}
{"_meta":{"uuid":"a580c83c-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.073230Z","level":"debug","message":"StartCommit","fields":{"build":"09c1bf210e819400","capture":"aliceCo/testing/source-hello-world","shard":"capture/aliceCo/testing/source-hello-world/00000000-00000000"}}
{"_meta":{"uuid":"a5838e8c-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.090986Z","level":"info","message":"initialized catalog task term","fields":{"labels":{"Build":"09c1bf210e819400","Hostname":"","LogLevel":4,"Range":{"key_end":4294967295,"r_clock_end":4294967295},"TaskName":"aliceCo/testing/source-hello-world","TaskType":1},"lastLabels":{"Build":"09c1bf210e819400","Hostname":"","LogLevel":4,"Range":{"key_end":4294967295,"r_clock_end":4294967295},"TaskName":"aliceCo/testing/source-hello-world","TaskType":1}}}
{"_meta":{"uuid":"a585be28-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.105037668Z","level":"info","message":"caught signal to exit","fields":{"module":"connector_init"}}
{"_meta":{"uuid":"a58654e6-efff-11ed-8400-311fcad51367"},"shard":{"kind":"capture","name":"aliceCo/testing/source-hello-world","keyBegin":"00000000","rClockBegin":"00000000"},"ts":"2023-05-11T13:27:59.109319959Z","level":"info","message":"connector-init exiting","fields":{"module":"flow_connector_init"}}
```

The docker container is also gone and a new one is started by the runtime

**Comment by psFried** [comment]
I feel like I must be missing something, because I don't see how this would work. It looks to me like `exit_status_task` is immediately locking the mutex and then waiting on the child to exit. Then if there's a timeout, we try to lock the mutex inside the `select!`. I don't see how that would work, since `exit_status_task` already holds the mutex lock until the child exits.

**Comment by mdibaiee** [comment]
@psFried it looks confusing... but it works because as soon as one of the branches of `select` resolves, the other branches of `select` are _cancelled_ by tokio, which means as soon as we are inside the timeout branch of `select`, `exit_status_task` is already cancelled and so the lock is released.

**Review by psFried — APPROVED** [review]
Thanks for the explanation. LGTM

**Pull request merged**
